<a href="https://colab.research.google.com/github/carlosfmorenog/CMM536_Data_Loading_Tutorial/blob/main/data_loading_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/carlosfmorenog/CMM536_Data_Loading_Tutorial  # clone the entire CMM536 repo

Cloning into 'CMM536'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 213 (delta 37), reused 45 (delta 16), pack-reused 121
Receiving objects: 100% (213/213), 130.75 MiB | 30.23 MiB/s, done.
Resolving deltas: 100% (59/59), done.


# Version 1: Converting your image repository into numpy arrays

In [ ]:
import os
import numpy as np
import cv2
resize_width = 100
resize_height = 100
path = '/content/CMM536_Data_Loading_Tutorial/data'
images = [] # List to append the images as 2D numpy arrays.
target = [] # List to append the target
originalrepo = [] # Create a repo for flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height)) 
                images.append(img)
                # Append the flattened image to the pixel repo
                originalrepo.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the repo list into numpy array
originalrepo = np.array(originalrepo) 
print(originalrepo)
print(target)

[[101 101 101 ... 178 176 182]
 [109 119 112 ...  12  14  34]
 [ 59  65  66 ... 127 132 111]
 [190 190 191 ...  38  37  38]
 [185 190 197 ... 146 146 146]
 [  8   9  11 ...  12   6 132]]
['mask', 'mask', 'mask', 'mask', 'nomask', 'nomask']


# Version 2: Converting your image repository into Pandas data frames

In [ ]:
import os
import numpy as np
import cv2
from pandas import DataFrame

resize_width = 25
resize_height = 25
path = '/content/CMM536/CMM536_Data_Loading_Tutorial/data'
images = [] # List to append the images as 2D numpy arrays
target =  []
originalrepo = [] # Create a repo for flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height)) 
                images.append(img)
                # Append the flattened image to the pixel repo
                originalrepo.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the repo list into pandas dataframe
originalrepowtarget = DataFrame(originalrepo) 
originalrepowtarget['class']=DataFrame(target)
originalrepowtarget

0    1    2    3    4    5    6  ...  619  620  621  622  623  624   class
0   97   95   92  -96 -103   78  -91  ...  -78  -80  -75  -71  -75  -74    mask
1 -119   40   80   92  -95  123 -121  ...   15   18   15   30   24   12    mask
2   63   83   49  108  -68   11   28  ...  -77  -78 -120  127  117 -128    mask
3  -66  -64  -66  -64  -64  -66  -63  ...   79   67   52   45   44   41    mask
4  -50 -101 -107 -103 -103 -103 -105  ... -107 -108 -110 -110 -110 -110  nomask
5   12   20    8   10   17    9   10  ...    4    9    8   10    9 -111  nomask

[6 rows x 626 columns]

It is up to you to use the one you like the most!